modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="rereskillable"
version="${file.jarVersion}"
displayName="Rereskillable"
displayURL=""
credits="Skillable and Reskillable"
authors="majik, LukeGrahamLandry, OrangeJewce92"
description='''
Rereskillable is a simplified rewrite of Reskillable for Minecraft Forge 1.16.5+.
'''

[[dependencies.rereskillable]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rereskillable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rereskillable]]
    modId="curios"
    mandatory=false
    versionRange="[1.20.1-5.7.2,)"
    ordering="AFTER"
    side="BOTH"